---
- name: Setup Slave Server With Python
  raw: sleep 30

- name: Run apt-get update
  raw: apt update -y

- name: Install Python 2
  raw: apt-get -y install -y python

- name: Ensure php packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php7.0
    - php7.0-mysql
    - php7.0-gd
    - php7.0-json
    - php7.0-mbstring
    - php7.0-mysql
    - libapache2-mod-php7.0
    - phpmyadmin
