sudo: required

services:
  - docker

# Use docker images which include systemd for valid testing
before_install:
  - 'sudo docker build --no-cache --rm --tag=ass2:ansible assignment2

jobs:
  include:
   - stage: prepare
     script: container_id=$(mktemp)
   - name: "Download containers"
     script: 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro ass2:ansible > "${container_id}"'
   - stage: linting
     name: "Check ansible playbook"
     script: 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -i hosts --connection=local ./ansible/site.yml --syntax-check'
   - stage: test
     name: Test single node Wordpress playbook
     script: 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -i hosts --connection=local ./ansible/site.yml'
   - stage: cleanup
     name: "rm containers"
     script: 'sudo docker rm -f "$(cat ${container_id})"'
