---
- name: Ensure mysql packages are installed
  apt:
    name: {{item}}
    state: present
  with_items:
    - mysql-server
    - php7.2-mysql

- name: Start mysql
  service:
    name: mysql
    state: started
