---
- name: Ensure mysql packages are installed
  apt:
    name: {{item}}
    state: present
  with_items:
    - php7.2
    - php7.2-mysql
    - php7.2-gd
    - php7.2-json
    - php7.2-mbstrin
    - phpmyadmin
